FROM liso_base:latest

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -d /home/$USERNAME -s /bin/bash \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN mkdir -p /home/$USERNAME

RUN echo "source activate liso" > ~/.bashrc

# Below this everything is run as regular user
USER $USERNAME

ENV PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

CMD [ "sleep", "infinity" ]

